version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Ameena
      MYSQL_DATABASE: cycleshop
      MYSQL_USER: Ameena
      MYSQL_PASSWORD: Ameena
  cycle:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cycleshop?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - db
  angular:
    build:
      context: /home/ameenajuhi/cycle-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - cycle
